// Code generated by mockery v2.5.1. DO NOT EDIT.

package mocks

import (
	models "ml-mutant-test/db/models"

	mock "github.com/stretchr/testify/mock"
)

// MutantServiceInterface is an autogenerated mock type for the MutantServiceInterface type
type MutantServiceInterface struct {
	mock.Mock
}

// IsMutant provides a mock function with given fields: dna
func (_m *MutantServiceInterface) IsMutant(dna []string) bool {
	ret := _m.Called(dna)

	var r0 bool
	if rf, ok := ret.Get(0).(func([]string) bool); ok {
		r0 = rf(dna)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Stats provides a mock function with given fields:
func (_m *MutantServiceInterface) Stats() (models.Stats, error) {
	ret := _m.Called()

	var r0 models.Stats
	if rf, ok := ret.Get(0).(func() models.Stats); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.Stats)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
